spring:
  application:
    name: heath
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcheckdb
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    
flyway:
  url: jdbc:postgresql://localhost:5432/postgresql
  schemas: log
  user: postgres
  password: itix.123
