CREATE TABLE public.status (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar NOT NULL,
	descricao varchar NOT NULL,
	CONSTRAINT status_pkey PRIMARY KEY (id)
);
CREATE INDEX status_id_idx ON public.status (id);