CREATE TABLE public.health (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	quando timestamp NOT NULL,
	ambienteid int8 NOT NULL,
	statusid int8 NOT NULL,
	clienteid int8 NOT NULL,
	CONSTRAINT health_pkey PRIMARY KEY (id),
	CONSTRAINT health_status_fkey FOREIGN KEY (statusid) REFERENCES public.status(id),
	CONSTRAINT health_cliente_fkey FOREIGN KEY (clienteid) REFERENCES public.cliente(id),
	CONSTRAINT health_ambiente_fkey FOREIGN KEY (ambienteid) REFERENCES public.ambiente(id)
);
CREATE INDEX health_id_idx ON public.health (id);